Which would you like to merge into (retain)?
<form action="?" method="POST">
    <?php echo $this->getBlockHtml('formkey')?>
    <input type="hidden" name="entity" value="<?=$this->getEntity()->getType()?>" />
    <?php
    foreach($_POST['selected'] as $selected)
    {
        ?>
        <input type="hidden" name="selected[]" value="<?=$selected?>" />
        <?php
    }
    foreach($this->requestLevels() as $level => $value)
    {
        ?>
        <input type="hidden" name="<?=$level?>" value="<?=$value?>" />
        <?php
    }
    
    foreach($this->slaveLevels as $vehicle)
    {
        echo '<input name="master" type="radio" value="' . $vehicle[1]->getValue($this->level) . '" />';
        echo $vehicle[0] . ': ' . $vehicle[1];
        echo '<br />';
    }
    ?>
    <input type="submit" value="Merge" />
</form>