<?php

$product = Mage::registry('current_product');

/** @todo move this out of templates */
/** Wrapped in function_exists() cuz Magento likes to include it 2x? */
if(!function_exists('isPainted')) {
    function isPainted($product)
    {
        $options = $product->getOptions();
        foreach($options as $option)
        {
             if('painted'==strtolower($option->getTitle()))
             {
                 return true;
             }
        }
        return false;
    }
}

if(!isPainted($product))
{
	return;
}
?>

<div class="paintOptions" align="center">
    <?php
    $selection = VF_Singleton::getInstance()->vehicleSelection();
    if( !$selection->isEmpty() )
    {
    	$leaf_id = $selection->getLeafValue();

        $vehicleFinder = new VF_Vehicle_Finder( new VF_Schema );
        $vehicle = $vehicleFinder->findByLeaf( $leaf_id );
        ?>
        <strong>Choose Painting Option For Your <?=$vehicle->__toString()?>:</strong>
        <br />
        <?php
        $mapper = new Elite_Vafpaint_Model_Paint_Mapper;
        $paint_codes = $mapper->findByFitId( $leaf_id );
        echo '<table class="vafPaintList">';
        foreach( $paint_codes as $paint )
        {
            echo '<tr>';
                echo '<td><input type="radio" name="paint" value="' . $paint->getId() . '" /></td>';
                echo '<td>' . $this->htmlEscape( $paint->getCode() ) . '</td>';
                echo '<td>' . $this->htmlEscape( $paint->getName() ) . '</td>';
                echo '<td style="background-color:' . $this->htmlEscape( $paint->getColor() ) . ';width:30px;border:1px #000 solid">&nbsp;</td>';
            echo '</tr>';
        }
        echo '<tr>';
        	echo '<td><input type="radio" name="paint" value="other" /></td>';
            echo '<td>OTHER</td>';
            echo '<td colspan="2">Custom Color Code
            	<input type="text" name="vafPaintCustom" value="" /></td>';
        echo '</tr>';
        echo '</table>';
    }
    else
    {
        ?>
        Select your vehicle to view paint availability.
        <?php
    }
    ?>
</div>


<script type="text/javascript" src="/skin/adminhtml/default/default/vf/jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="/skin/adminhtml/default/default/vf/vafPaint.js"></script>