<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('catalog')->__( 'Import Vehicles List' ) ?></h4>
    </div>
    <fieldset>
                 
        <legend><?php echo Mage::helper('catalog')->__('Import Vehicles List') ?></legend>
        <?php echo $this->messages; ?>
        <form action="?" method="post" enctype="multipart/form-data">
            <?php echo $this->getBlockHtml('formkey')?>
            <input type="file" name="file" />
            <br />
            <strong>Format:</strong>
            <input type="radio" name="format" value="CSV" checked="checked">CSV<br />
            <input type="radio" name="format" value="XML">XML <span style="color: red;">(Beta)</span> <br />
            <br />
            <input type="submit" name="submit" value="Import" />
        </form>
    </fieldset>
</div>