<?php
$schema = new VF_Schema();
$levels = isset( $_REQUEST['levels'] ) ? $_REQUEST['levels'] : implode(',',$schema->getLevels());
?>

<style type="text/css">
.vafSchemaForm fieldset
{
    border:1px #000 solid;
    padding:5px;
}
.vafSchemaForm legend
{
    display:block;
}
</style>

<form action="?" class="vafSchemaForm">
    <fieldset>
        <legend>Change Levels</legend>
        Type name of new levels seperated by comma:
        <input type="text" name="levels" size="40" value="<?=$levels?>" /> (ex. "make,model, year")
        <br />
        <strong>Warning:</strong> pressing submit will clear out any & all loaded data. Back up mappings+definitions files first.
        <br /><input name="submit" type="submit" value="Create New Schema" />
    </fieldset>
</form>

<form action="?" class="vafSchemaForm">
    <fieldset>
        <legend>Change Sort Orders</legend>
    
        <?php
        foreach( $schema->getLevels() as $level )
        {
            ?>
            <div>
                <dl>
                    <dd><label><?=ucfirst($level)?> Sort Direction</label></dd>
                    <dt>
                        <select name="<?=$level?>Sorting">
                            <option value="asc" <?=$schema->getSorting($level) == 'asc' ? ' selected="selected"' : ''?>>Ascending (A to Z)</option>
                            <option value="desc" <?=$schema->getSorting($level) == 'desc' ? ' selected="selected"' : ''?>>Descending (Z to A)</option>
                        </select>
                    </dt>
                </dl>
                    
            </div>
            <?php
        }
        ?>
        <br /><input name="submit" type="submit" value="Save" />
    </fieldset>
</form> 