<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Fitment Settings') ?></h4>
    </div>
    <fieldset>
        <input type="checkbox" id="universal" name="universal" <?= $this->getProduct()->isUniversal() ? ' checked="checked"' : '' ?> value="1" />
        Universal Product
        <br />
	<?php
        if( file_exists(ELITE_PATH.'/Vafrelated') )
        {
            $relatedProduct = new Elite_Vafrelated_Model_Catalog_Product($this->getProduct());
            ?>
            <input type="checkbox" id="related" name="related" <?= $relatedProduct->showInRelated() ? ' checked="checked"' : '' ?> value="1" />
            Show In Automotive Related Products
            <?php
        }
        ?>
    </fieldset>
</div>

<?=$this->renderConfigurations()?>

<div id="vaf-toggle">    
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Add New Vehicle Fit') ?></h4>
        </div>
         <?=$this->renderMultiTree()?>
    </div>

</div>

<!-- start VAF -->
<script src="/skin/adminhtml/default/default/jquery-1.7.1.min.js" type="text/javascript" language="javascript"></script>
<script type="text/javascript" language="javascript">
 jQuery.noConflict();
</script>
<script src="<?=Mage::getBaseUrl()?>vaf/ajax/js?unavailableSelections=<?=$this->unavailableSelections()?>" type="text/javascript" language="javascript"></script>
<script src="/skin/adminhtml/default/default/jquery.metadata.pack.js" type="text/javascript" language="javascript"></script>
<link rel="stylesheet" type="text/css" href="/skin/adminhtml/default/default/multiTree.css" />
<!-- end VAF -->