<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('catalog')->__( 'Import Vehicle Bolt Patterns' ) ?></h4>
    </div>
    <fieldset>
                 
        <legend><?php echo Mage::helper('catalog')->__('Import Vehicle Bolt Patterns') ?></legend>
        <?php echo $this->messages; ?>
        <form action="?" method="post" enctype="multipart/form-data">
            <?php echo $this->getBlockHtml('formkey')?>
            <input type="file" name="file" />
            <br />
            <input type="submit" name="submit" value="Import" />
        </form>
    </fieldset>
</div>